// Basic keycodes. These are sent via Keyboard/Keypad.
#define KC_NO              0x00
#define KC_ROLL_OVER       0x01
#define KC_POST_FAIL       0x02
#define KC_UNDEFINED       0x03
#define KC_A               0x04
#define KC_B               0x05
#define KC_C               0x06
#define KC_D               0x07
#define KC_E               0x08
#define KC_F               0x09
#define KC_G               0x0A
#define KC_H               0x0B
#define KC_I               0x0C
#define KC_J               0x0D
#define KC_K               0x0E
#define KC_L               0x0F
#define KC_M               0x10
#define KC_N               0x11
#define KC_O               0x12
#define KC_P               0x13
#define KC_Q               0x14
#define KC_R               0x15
#define KC_S               0x16
#define KC_T               0x17
#define KC_U               0x18
#define KC_V               0x19
#define KC_W               0x1A
#define KC_X               0x1B
#define KC_Y               0x1C
#define KC_Z               0x1D
#define KC_1               0x1E
#define KC_2               0x1F
#define KC_3               0x20
#define KC_4               0x21
#define KC_5               0x22
#define KC_6               0x23
#define KC_7               0x24
#define KC_8               0x25
#define KC_9               0x26
#define KC_0               0x27
#define KC_ENTER           0x28
#define KC_ESCAPE          0x29
#define KC_BACKSPACE       0x2A
#define KC_TAB             0x2B
#define KC_SPACE           0x2C
#define KC_MINUS           0x2D
#define KC_EQUAL           0x2E
#define KC_LBRACKET        0x2F
#define KC_RBRACKET        0x30
#define KC_BSLASH          0x31
#define KC_NONUS_HASH      0x32
#define KC_SCOLON          0x33
#define KC_QUOTE           0x34
#define KC_GRAVE           0x35
#define KC_COMMA           0x36
#define KC_DOT             0x37
#define KC_SLASH           0x38
#define KC_CAPSLOCK        0x39
#define KC_F1              0x3A
#define KC_F2              0x3B
#define KC_F3              0x3C
#define KC_F4              0x3D
#define KC_F5              0x3E
#define KC_F6              0x3F
#define KC_F7              0x40
#define KC_F8              0x41
#define KC_F9              0x42
#define KC_F10             0x43
#define KC_F11             0x44
#define KC_F12             0x45
#define KC_PSCREEN         0x46
#define KC_SCROLLLOCK      0x47
#define KC_PAUSE           0x48
#define KC_INSERT          0x49
#define KC_HOME            0x4A
#define KC_PGUP            0x4B
#define KC_DELETE          0x4C
#define KC_END             0x4D
#define KC_PGDOWN          0x4E
#define KC_RIGHT           0x4F
#define KC_LEFT            0x50
#define KC_DOWN            0x51
#define KC_UP              0x52
#define KC_NUMLOCK         0x53
#define KC_KP_SLASH        0x54
#define KC_KP_ASTERISK     0x55
#define KC_KP_MINUS        0x56
#define KC_KP_PLUS         0x57
#define KC_KP_ENTER        0x58
#define KC_KP_1            0x59
#define KC_KP_2            0x5A
#define KC_KP_3            0x5B
#define KC_KP_4            0x5C
#define KC_KP_5            0x5D
#define KC_KP_6            0x5E
#define KC_KP_7            0x5F
#define KC_KP_8            0x60
#define KC_KP_9            0x61
#define KC_KP_0            0x62
#define KC_KP_DOT          0x63
#define KC_NONUS_BSLASH    0x64
#define KC_APPLICATION     0x65
#define KC_POWER           0x66
#define KC_KP_EQUAL        0x67
#define KC_F13             0x68
#define KC_F14             0x69
#define KC_F15             0x6A
#define KC_F16             0x6B
#define KC_F17             0x6C
#define KC_F18             0x6D
#define KC_F19             0x6E
#define KC_F20             0x6F
#define KC_F21             0x70
#define KC_F22             0x71
#define KC_F23             0x72
#define KC_F24             0x73
#define KC_EXECUTE         0x74
#define KC_HELP            0x75
#define KC_MENU            0x76
#define KC_SELECT          0x77
#define KC_STOP            0x78
#define KC_AGAIN           0x79
#define KC_UNDO            0x7A
#define KC_CUT             0x7B
#define KC_COPY            0x7C
#define KC_PASTE           0x7D
#define KC_FIND            0x7E
#define KC_MUTE            0x7F
#define KC_VOL_UP          0x80
#define KC_VOL_DOWN        0x81
#define KC_LOCK_CAPS       0x82
#define KC_LOCK_NUM        0x83
#define KC_LOCK_SCROLL     0x84
#define KC_KP_COMMA        0x85
#define KC_KP_EQUAL_AS400  0x86
#define KC_INTL1           0x87
#define KC_INTL2           0x88
#define KC_INTL3           0x89
#define KC_INTL4           0x8A
#define KC_INTL5           0x8B
#define KC_INTL6           0x8C
#define KC_INTL7           0x8D
#define KC_INTL8           0x8E
#define KC_INTL9           0x8F
#define KC_LANG1           0x90
#define KC_LANG2           0x91
#define KC_LANG3           0x92
#define KC_LANG4           0x93
#define KC_LANG5           0x94
#define KC_LANG6           0x95
#define KC_LANG7           0x96
#define KC_LANG8           0x97
#define KC_LANG9           0x98
#define KC_ALT_ERASE       0x99
#define KC_SYSREQ          0x9A
#define KC_CANCEL          0x9B
#define KC_CLEAR           0x9C
#define KC_PRIOR           0x9D
#define KC_RETURN          0x9E
#define KC_SEPARATOR       0x9F
#define KC_OUT             0xA0
#define KC_OPER            0xA1
#define KC_CLEAR_AGAIN     0xA2
#define KC_CRSEL           0xA3
#define KC_EXSEL           0xA4
#define KC_KP_00           0xB0
#define KC_KP_000          0xB1
#define KC_THOUSANDS_SEP   0xB2
#define KC_DECIMAL_SEP     0xB3
#define KC_CURRENCY_UNIT   0xB4
#define KC_CURRENCY_SUB    0xB5
#define KC_KP_LPAREN       0xB6
#define KC_KP_RPAREN       0xB7
#define KC_KP_LBRACE       0xB8
#define KC_KP_RBRACE       0xB9
#define KC_KP_TAB          0xBA
#define KC_KP_BSPACE       0xBB
#define KC_KP_A            0xBC
#define KC_KP_B            0xBD
#define KC_KP_C            0xBE
#define KC_KP_D            0xBF
#define KC_KP_E            0xC0
#define KC_KP_F            0xC1
#define KC_KP_XOR          0xC2
#define KC_KP_CARET        0xC3
#define KC_KP_PERCENT      0xC4
#define KC_KP_LT           0xC5
#define KC_KP_GT           0xC6
#define KC_KP_AMP          0xC7
#define KC_KP_AND          0xC8
#define KC_KP_PIPE         0xC9
#define KC_KP_OR           0xCA
#define KC_KP_COLON        0xCB
#define KC_KP_HASH         0xCC
#define KC_KP_SPACE        0xCD
#define KC_KP_AT           0xCE
#define KC_KP_EXCLAMATION  0xCF
#define KC_KP_MEM_STORE    0xD0
#define KC_KP_MEM_RECALL   0xD1
#define KC_KP_MEM_CLEAR    0xD2
#define KC_KP_MEM_ADD      0xD3
#define KC_KP_MEM_SUB      0xD4
#define KC_KP_MEM_MUL      0xD5
#define KC_KP_MEM_DIV      0xD6
#define KC_KP_PLUS_MINUS   0xD7
#define KC_KP_CLEAR        0xD8
#define KC_KP_CLEAR_ENTRY  0xD9
#define KC_KP_BINARY       0xDA
#define KC_KP_OCTAL        0xDB
#define KC_KP_DECIMAL      0xDC
#define KC_KP_HEXADECIMAL  0xDD
#define KC_LCTRL           0xE0
#define KC_LSHIFT          0xE1
#define KC_LALT            0xE2
#define KC_LGUI            0xE3
#define KC_RCTRL           0xE4
#define KC_RSHIFT          0xE5
#define KC_RALT            0xE6
#define KC_RGUI            0xE7

// Media keys. These are sent via Consumer Control.
#define KC_MEDIA_PLAY      0xE8
#define KC_MEDIA_STOP      0xE9
#define KC_MEDIA_PREV      0xEA
#define KC_MEDIA_NEXT      0xEB
#define KC_MEDIA_EJECT     0xEC
#define KC_MEDIA_VOL_UP    0xED
#define KC_MEDIA_VOL_DOWN  0xEE
#define KC_MEDIA_MUTE      0xEF
#define KC_MEDIA_WWW       0xF0
#define KC_MEDIA_BACK      0xF1
#define KC_MEDIA_FORWARD   0xF2
#define KC_MEDIA_CANCEL    0xF3
#define KC_MEDIA_SEARCH    0xF4
#define KC_MEDIA_SLEEP     0xF8
#define KC_MEDIA_LOCK      0xF9
#define KC_MEDIA_RELOAD    0xFA
#define KC_CALC            0xFB
